# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20170405_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
