# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20170408_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
